import type { PassCliRunner } from "../pass-cli/runner.js";
import {
  createCreditCardItemHandler,
  createCreditCardItemInputSchema,
  createCustomItemHandler,
  createCustomItemInputSchema,
  createIdentityItemHandler,
  createIdentityItemInputSchema,
  createItemAliasHandler,
  createItemAliasInputSchema,
  createLoginItemFromTemplateHandler,
  createLoginItemFromTemplateInputSchema,
  createLoginItemHandler,
  createLoginItemInputSchema,
  createNoteItemHandler,
  createNoteItemInputSchema,
  createWifiItemHandler,
  createWifiItemInputSchema,
  deleteItemHandler,
  deleteItemInputSchema,
  downloadItemAttachmentHandler,
  downloadItemAttachmentInputSchema,
  itemTotpHandler,
  itemTotpInputSchema,
  listItemMembersHandler,
  listItemMembersInputSchema,
  listItemsHandler,
  listItemsInputSchema,
  moveItemHandler,
  moveItemInputSchema,
  removeItemMemberHandler,
  removeItemMemberInputSchema,
  searchItemsHandler,
  searchItemsInputSchema,
  shareItemHandler,
  shareItemInputSchema,
  trashItemHandler,
  trashItemInputSchema,
  untrashItemHandler,
  untrashItemInputSchema,
  updateItemHandler,
  updateItemInputSchema,
  updateItemMemberHandler,
  updateItemMemberInputSchema,
  viewItemHandler,
  viewItemInputSchema,
} from "../tools/item.js";
import { inputTool, type ToolDefinition } from "./tool-definition-types.js";

export function createItemToolDefinitions(passCli: PassCliRunner): ToolDefinition[] {
  return [
    inputTool(
      "list_items",
      "List items for a vault or share with MCP pagination support for JSON output.",
      listItemsInputSchema,
      (input) => listItemsHandler(passCli, input),
    ),
    inputTool(
      "view_item",
      "View a specific item by URI or selectors, optionally returning a specific field.",
      viewItemInputSchema,
      (input) => viewItemHandler(passCli, input),
    ),
    inputTool(
      "generate_item_totp",
      "Generate TOTP code(s) for an item by URI or selectors, optionally targeting a specific field.",
      itemTotpInputSchema,
      (input) => itemTotpHandler(passCli, input),
    ),
    inputTool(
      "create_login_item",
      "Create a login item in a vault or share.",
      createLoginItemInputSchema,
      (input) => createLoginItemHandler(passCli, input),
    ),
    inputTool(
      "create_login_item_from_template",
      "Create a login item from template JSON.",
      createLoginItemFromTemplateInputSchema,
      (input) => createLoginItemFromTemplateHandler(passCli, input),
    ),
    inputTool(
      "create_note_item",
      "Create a note item in a vault or share.",
      createNoteItemInputSchema,
      (input) => createNoteItemHandler(passCli, input),
    ),
    inputTool(
      "create_credit_card_item",
      "Create a credit card item in a vault or share.",
      createCreditCardItemInputSchema,
      (input) => createCreditCardItemHandler(passCli, input),
    ),
    inputTool(
      "create_wifi_item",
      "Create a WiFi item in a vault or share.",
      createWifiItemInputSchema,
      (input) => createWifiItemHandler(passCli, input),
    ),
    inputTool(
      "create_custom_item",
      "Create a custom item from template payload in a vault or share.",
      createCustomItemInputSchema,
      (input) => createCustomItemHandler(passCli, input),
    ),
    inputTool(
      "create_identity_item",
      "Create an identity item from template payload in a vault or share.",
      createIdentityItemInputSchema,
      (input) => createIdentityItemHandler(passCli, input),
    ),
    inputTool(
      "move_item",
      "Move an item from one vault to another.",
      moveItemInputSchema,
      (input) => moveItemHandler(passCli, input),
    ),
    inputTool(
      "update_item",
      "Update an item using selectors and field assignments.",
      updateItemInputSchema,
      (input) => updateItemHandler(passCli, input),
    ),
    inputTool("trash_item", "Move an item to trash by selectors.", trashItemInputSchema, (input) =>
      trashItemHandler(passCli, input),
    ),
    inputTool(
      "untrash_item",
      "Restore an item from trash by selectors.",
      untrashItemInputSchema,
      (input) => untrashItemHandler(passCli, input),
    ),
    inputTool(
      "delete_item",
      "Delete an item by share ID and item ID.",
      deleteItemInputSchema,
      (input) => deleteItemHandler(passCli, input),
    ),
    inputTool(
      "download_item_attachment",
      "Download an item attachment to a local path.",
      downloadItemAttachmentInputSchema,
      (input) => downloadItemAttachmentHandler(passCli, input),
    ),
    inputTool(
      "create_item_alias",
      "Create an email alias item.",
      createItemAliasInputSchema,
      (input) => createItemAliasHandler(passCli, input),
    ),
    inputTool("list_item_members", "List item members.", listItemMembersInputSchema, (input) =>
      listItemMembersHandler(passCli, input),
    ),
    inputTool(
      "update_item_member",
      "Update an item member role.",
      updateItemMemberInputSchema,
      (input) => updateItemMemberHandler(passCli, input),
    ),
    inputTool(
      "remove_item_member",
      "Remove an item member.",
      removeItemMemberInputSchema,
      (input) => removeItemMemberHandler(passCli, input),
    ),
    inputTool("share_item", "Share an item with a user.", shareItemInputSchema, (input) =>
      shareItemHandler(passCli, input),
    ),
    inputTool(
      "search_items",
      "Search items by title with MCP pagination support for JSON output.",
      searchItemsInputSchema,
      (input) => searchItemsHandler(passCli, input),
    ),
  ];
}
