#!/usr/bin/env tsx

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { toCommandKey, WRAPPED_COMMAND_PREFIXES } from "../src/pass-cli/command-catalog.js";

type OutputSemantics = "none" | "format" | "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, "..");
const outputPolicyJsonPath = resolve(rootDir, "src/pass-cli/output-policy.json");
const outputPolicyGeneratedPath = resolve(rootDir, "src/pass-cli/output-policy.generated.ts");
const passCliBin = process.env.PASS_CLI_BIN || "pass-cli";
const mode = process.argv.includes("--write") ? "write" : "check";

function probeHelp(parts: readonly string[]): string {
  try {
    return execFileSync(passCliBin, [...parts, "--help"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
  } catch (error) {
    const stderr = String((error as { stderr?: unknown }).stderr ?? "").trim();
    const stdout = String((error as { stdout?: unknown }).stdout ?? "").trim();
    const details = [stderr, stdout].filter(Boolean).join("\n");
    throw new Error(
      `Failed to probe "${toCommandKey(parts)} --help" with "${passCliBin}".` +
        (details ? `\n${details}` : ""),
      { cause: error },
    );
  }
}

function classifyOutputSemantics(
  helpText: string,
  commandParts: readonly string[],
): OutputSemantics {
  const lines = helpText
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.includes("--output"));

  if (lines.length === 0) return "none";

  const lowerLines = lines.map((line) => line.toLowerCase());
  if (lowerLines.some((line) => line.includes("output path"))) return "path";
  if (
    lowerLines.some(
      (line) => line.includes("possible values: human, json") || line.includes("output format"),
    )
  ) {
    return "format";
  }

  throw new Error(
    `Could not classify output semantics for "${toCommandKey(commandParts)}".\n` +
      `Matched lines:\n${lines.map((line) => `  ${line}`).join("\n")}`,
  );
}

function buildSemanticsByCommand(): Record<string, OutputSemantics> {
  const semanticsByCommand: Record<string, OutputSemantics> = {};
  const seen = new Set<string>();

  for (const parts of WRAPPED_COMMAND_PREFIXES) {
    const key = toCommandKey(parts);
    if (seen.has(key)) continue;
    seen.add(key);
    semanticsByCommand[key] = classifyOutputSemantics(probeHelp(parts), parts);
  }

  return semanticsByCommand;
}

function toPrefixLiteral(parts: readonly string[]): string {
  return `  [${parts.map((part) => JSON.stringify(part)).join(", ")}],`;
}

function buildOutputPolicyJsonText(semanticsByCommand: Record<string, OutputSemantics>): string {
  return `${JSON.stringify(
    {
      semanticsByCommand,
    },
    null,
    2,
  )}\n`;
}

function buildGeneratedTsText(semanticsByCommand: Record<string, OutputSemantics>): string {
  const formatPrefixes: readonly string[][] = [];
  const pathPrefixes: readonly string[][] = [];

  for (const prefix of WRAPPED_COMMAND_PREFIXES) {
    const semantics = semanticsByCommand[toCommandKey(prefix)];
    if (semantics === "format") formatPrefixes.push(prefix);
    if (semantics === "path") pathPrefixes.push(prefix);
  }

  return [
    "/*",
    " * AUTO-GENERATED by scripts/sync-pass-cli-output-policy.ts",
    " * Do not edit manually. Run:",
    " *   npm run pass:dev:output-policy:update",
    " */",
    "",
    "export const FORMAT_OUTPUT_COMMAND_PREFIXES: readonly (readonly string[])[] = [",
    ...formatPrefixes.map((prefix) => toPrefixLiteral(prefix)),
    "];",
    "",
    "export const PATH_OUTPUT_COMMAND_PREFIXES: readonly (readonly string[])[] = [",
    ...pathPrefixes.map((prefix) => toPrefixLiteral(prefix)),
    "];",
    "",
  ].join("\n");
}

function writeOrCheck(path: string, expected: string): boolean {
  const current = (() => {
    try {
      return readFileSync(path, "utf8");
    } catch {
      return "";
    }
  })();

  const changed = current !== expected;
  if (!changed) return false;

  if (mode === "write") {
    writeFileSync(path, expected, "utf8");
    return true;
  }

  return true;
}

function main() {
  const semanticsByCommand = buildSemanticsByCommand();
  const jsonText = buildOutputPolicyJsonText(semanticsByCommand);
  const generatedTsText = buildGeneratedTsText(semanticsByCommand);

  const changedJson = writeOrCheck(outputPolicyJsonPath, jsonText);
  const changedGenerated = writeOrCheck(outputPolicyGeneratedPath, generatedTsText);
  const changed = changedJson || changedGenerated;

  if (mode === "write") {
    if (!changed) {
      process.stdout.write("Output policy artifacts already up to date.\n");
      return;
    }
    process.stdout.write(
      "Updated src/pass-cli/output-policy.json and src/pass-cli/output-policy.generated.ts.\n",
    );
    return;
  }

  if (changed) {
    process.stderr.write(
      "Output policy artifacts are out of date. Run:\n" +
        "  npm run pass:dev:output-policy:update\n",
    );
    process.exitCode = 1;
    return;
  }

  process.stdout.write("Output policy artifacts are up to date.\n");
}

main();
