export const WRAPPED_COMMAND_PREFIXES = [
  ["info"],
  ["user", "info"],
  ["test"],
  ["settings", "view"],
  ["settings", "set", "default-vault"],
  ["settings", "unset", "default-vault"],
  ["inject"],
  ["run"],
  ["invite", "list"],
  ["invite", "accept"],
  ["invite", "reject"],
  ["password", "generate", "random"],
  ["password", "generate", "passphrase"],
  ["password", "score"],
  ["totp", "generate"],
  ["share", "list"],
  ["vault", "list"],
  ["vault", "member", "list"],
  ["vault", "create"],
  ["vault", "update"],
  ["vault", "share"],
  ["vault", "delete"],
  ["vault", "member", "update"],
  ["vault", "member", "remove"],
  ["vault", "transfer"],
  ["item", "list"],
  ["item", "view"],
  ["item", "totp"],
  ["item", "create", "login"],
  ["item", "create", "note"],
  ["item", "create", "credit-card"],
  ["item", "create", "wifi"],
  ["item", "create", "custom"],
  ["item", "create", "identity"],
  ["item", "alias", "create"],
  ["item", "share"],
  ["item", "member", "list"],
  ["item", "member", "update"],
  ["item", "member", "remove"],
  ["item", "move"],
  ["item", "update"],
  ["item", "trash"],
  ["item", "untrash"],
  ["item", "attachment", "download"],
  ["item", "delete"],
] as const satisfies readonly (readonly string[])[];

export type WrappedCommandPrefix = (typeof WRAPPED_COMMAND_PREFIXES)[number];

export function toCommandKey(parts: readonly string[]): string {
  return parts.join(" ");
}
