/*
 * AUTO-GENERATED by scripts/sync-pass-cli-output-policy.ts
 * Do not edit manually. Run:
 *   npm run pass:dev:output-policy:update
 */

export const FORMAT_OUTPUT_COMMAND_PREFIXES: readonly (readonly string[])[] = [
  ["info"],
  ["user", "info"],
  ["invite", "list"],
  ["password", "generate", "random"],
  ["password", "generate", "passphrase"],
  ["password", "score"],
  ["totp", "generate"],
  ["share", "list"],
  ["vault", "list"],
  ["vault", "member", "list"],
  ["item", "list"],
  ["item", "view"],
  ["item", "totp"],
  ["item", "alias", "create"],
  ["item", "member", "list"],
];

export const PATH_OUTPUT_COMMAND_PREFIXES: readonly (readonly string[])[] = [
  ["item", "attachment", "download"],
];
